package com.bureaueye.beacon.bean.standard;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the address table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="address"
 */
public final class Address {


	// primary key
	private java.lang.String _addrkey;

	// fields
	private java.lang.String _name;
	private java.lang.String _typekey;

	private java.lang.String _shortname;
	
	private java.lang.String _longLabel;
	private java.lang.String _shortLabel;
	
	// constructors
	public Address (
			com.bureaueye.beacon.model.standard.Address address
			) {
		String name = address.getName();
		try {name = address.getName().substring(0,30);}catch(Exception e){}
		this._longLabel = 	address.getName()+" "+"["+address.getTypekey().toLowerCase()+"]";
		this._addrkey = address.getAddrkey();
		this._name = address.getName();
		this._shortname = address.getShortname();

		String shortname = address.getShortname();
		try {shortname = address.getShortname().substring(0,18);}catch(Exception e){}
		String typekey = address.getTypekey();
		try {typekey = address.getTypekey().substring(0,3);}catch(Exception e){}
		this._shortLabel = 	shortname+" "+"["+typekey.toLowerCase()+"]";
	}

	/**
     */
	public java.lang.String getLongLabel () {
		return _longLabel;
	}
	/**
	 */
	public void setLongLabel (java.lang.String _longLabel) {
		this._longLabel = _longLabel;
	}

	/**
     */
	public java.lang.String getShortLabel () {
		return _shortLabel;
	}
	/**
	 */
	public void setShortLabel (java.lang.String _shortLabel) {
		this._shortLabel = _shortLabel;
	}
	
	/**
     */
	public java.lang.String getShortname () {
		return _shortname;
	}
	/**
	 */
	public void setShortname (java.lang.String _shortname) {
		this._shortname = _shortname;
	}
	
	
	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="assigned"
     *  column="addrkey"
     */
	public java.lang.String getAddrkey () {
		return _addrkey;
	}
	public void setAddrkey (String _addrkey) {
		this._addrkey = _addrkey;
	}

	public java.lang.String getName () {
		return _name;
	}
	public void setName (String _name) {
		this._name = _name;
	}
	
	public java.lang.String getTypekey () {
		return _typekey;
	}
	public void setTypekey (String _typekey) {
		this._typekey = _typekey;
	}
	
	
	public String toString () {
		return super.toString();
	}
	
}