package com.bureaueye.beacon.bean.standard;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the location table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="location"
 */
public final class Location  {

	// primary key
	private java.lang.String _locationkey;

	// fields
	private java.lang.String _description2;
	private java.lang.String _city;
	private java.lang.String _fax;
	private java.lang.String _portUnicon;
	private java.lang.String _postalCode;
	private java.lang.String _description3;
	private java.lang.String _state;
	private java.lang.String _address1;
	private java.lang.String _locationName;
	private java.lang.String _shortName;	
	private java.lang.String _phone;
	private java.lang.String _description1;
	private java.lang.String _plantCode;
	private java.lang.String _locationType;
	private java.lang.String _address3;
	private java.lang.String _address2;	
	private java.lang.String _contact;
	private java.lang.String _country;

	private java.lang.String _labelProperty;

	private java.lang.String _longLabel;
	private java.lang.String _shortLabel;
	
	// constructors
	public Location (com.bureaueye.beacon.model.standard.Location location) {
		String locationName = location.getLocationName();
		if (locationName.equals("")) locationName = "BLANK NAME";
		try {locationName = location.getLocationName().substring(0,20);}catch(Exception e){}
		this._labelProperty = 	locationName+
								" > "+location.getCity()+
								" ["+location.getLocationType().toLowerCase()+"]";
		this._locationkey = location.getLocationkey();
		this._locationName = location.getLocationName();
		this._shortName = location.getShortName();
		
		String shortname = location.getShortName();
		try {shortname = shortname.substring(0,17);}catch(Exception e){}
		String shortcity = location.getCity();
		try {shortcity = shortcity.substring(0,8);}catch(Exception e){}
		String shortcountry = location.getCountry();
		try {shortcountry = shortcountry.substring(0,10);}catch(Exception e){}		
		this._shortLabel = 	shortname+" > "+shortcity;
		this._longLabel = 	location.getShortName()+" > "+location.getCity()+" > "+location.getCountry();
	}


	/**
     */
	public java.lang.String getLabelProperty () {
		return _labelProperty;
	}
	/**
	 */
	public void setLabelProperty (java.lang.String _labelProperty) {
		this._labelProperty = _labelProperty;
	}
	
	/**
     */
	public java.lang.String getLongLabel () {
		return _longLabel;
	}
	/**
	 */
	public void setLongLabel (java.lang.String _longLabel) {
		this._longLabel = _longLabel;
	}

	/**
     */
	public java.lang.String getShortLabel () {
		return _shortLabel;
	}
	/**
	 */
	public void setShortLabel (java.lang.String _shortLabel) {
		this._shortLabel = _shortLabel;
	}
	
	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="assigned"
     *  column="Locationkey"
     */
	public java.lang.String getLocationkey () {
		return _locationkey;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _locationkey the new ID
	 */
	public void setLocationkey (java.lang.String _locationkey) {
		this._locationkey = _locationkey;
	}


	/**
	 * Return the value associated with the column: Description2
	 */
	public java.lang.String getDescription2 () {
		return _description2;
	}

	/**
	 * Set the value related to the column: Description2
	 * @param _description2 the Description2 value
	 */
	public void setDescription2 (java.lang.String _description2) {
		this._description2 = _description2;
	}


	/**
	 * Return the value associated with the column: City
	 */
	public java.lang.String getCity () {
		return _city;
	}

	/**
	 * Set the value related to the column: City
	 * @param _city the City value
	 */
	public void setCity (java.lang.String _city) {
		this._city = _city;
	}



	/**
	 * Return the value associated with the column: Fax
	 */
	public java.lang.String getFax () {
		return _fax;
	}

	/**
	 * Set the value related to the column: Fax
	 * @param _fax the Fax value
	 */
	public void setFax (java.lang.String _fax) {
		this._fax = _fax;
	}


	/**
	 * Return the value associated with the column: PortUnicon
	 */
	public java.lang.String getPortUnicon () {
		return _portUnicon;
	}

	/**
	 * Set the value related to the column: PortUnicon
	 * @param _portUnicon the PortUnicon value
	 */
	public void setPortUnicon (java.lang.String _portUnicon) {
		this._portUnicon = _portUnicon;
	}


	/**
	 * Return the value associated with the column: PostalCode
	 */
	public java.lang.String getPostalCode () {
		return _postalCode;
	}

	/**
	 * Set the value related to the column: PostalCode
	 * @param _postalCode the PostalCode value
	 */
	public void setPostalCode (java.lang.String _postalCode) {
		this._postalCode = _postalCode;
	}


	/**
	 * Return the value associated with the column: Description3
	 */
	public java.lang.String getDescription3 () {
		return _description3;
	}

	/**
	 * Set the value related to the column: Description3
	 * @param _description3 the Description3 value
	 */
	public void setDescription3 (java.lang.String _description3) {
		this._description3 = _description3;
	}


	/**
	 * Return the value associated with the column: State
	 */
	public java.lang.String getState () {
		return _state;
	}

	/**
	 * Set the value related to the column: State
	 * @param _state the State value
	 */
	public void setState (java.lang.String _state) {
		this._state = _state;
	}


	/**
	 * Return the value associated with the column: Address1
	 */
	public java.lang.String getAddress1 () {
		return _address1;
	}

	/**
	 * Set the value related to the column: Address1
	 * @param _address1 the Address1 value
	 */
	public void setAddress1 (java.lang.String _address1) {
		this._address1 = _address1;
	}


	/**
	 * Return the value associated with the column: LocationName
	 */
	public java.lang.String getLocationName () {
		return _locationName;
	}

	/**
	 * Set the value related to the column: LocationName
	 * @param _locationName the LocationName value
	 */
	public void setLocationName (java.lang.String _locationName) {
		this._locationName = _locationName;
	}

	
	/**
	 * Return the value associated with the column: ShortName
	 */
	public java.lang.String getShortName () {
		return _shortName;
	}

	/**
	 * Set the value related to the column: ShortName
	 * @param _shortName the ShortName value
	 */
	public void setShortName (java.lang.String _shortName) {
		this._shortName = _shortName;
	}

	
	

	/**
	 * Return the value associated with the column: Phone
	 */
	public java.lang.String getPhone () {
		return _phone;
	}

	/**
	 * Set the value related to the column: Phone
	 * @param _phone the Phone value
	 */
	public void setPhone (java.lang.String _phone) {
		this._phone = _phone;
	}


	/**
	 * Return the value associated with the column: Description1
	 */
	public java.lang.String getDescription1 () {
		return _description1;
	}

	/**
	 * Set the value related to the column: Description1
	 * @param _description1 the Description1 value
	 */
	public void setDescription1 (java.lang.String _description1) {
		this._description1 = _description1;
	}


	/**
	 * Return the value associated with the column: PlantCode
	 */
	public java.lang.String getPlantCode () {
		return _plantCode;
	}

	/**
	 * Set the value related to the column: PlantCode
	 * @param _plantCode the PlantCode value
	 */
	public void setPlantCode (java.lang.String _plantCode) {
		this._plantCode = _plantCode;
	}


	/**
	 * Return the value associated with the column: LocationType
	 */
	public java.lang.String getLocationType () {
		return _locationType;
	}

	/**
	 * Set the value related to the column: LocationType
	 * @param _locationType the LocationType value
	 */
	public void setLocationType (java.lang.String _locationType) {
		this._locationType = _locationType;
	}


	/**
	 * Return the value associated with the column: Address3
	 */
	public java.lang.String getAddress3 () {
		return _address3;
	}

	/**
	 * Set the value related to the column: Address3
	 * @param _address3 the Address3 value
	 */
	public void setAddress3 (java.lang.String _address3) {
		this._address3 = _address3;
	}


	/**
	 * Return the value associated with the column: Contact
	 */
	public java.lang.String getContact () {
		return _contact;
	}

	/**
	 * Set the value related to the column: Contact
	 * @param _contact the Contact value
	 */
	public void setContact (java.lang.String _contact) {
		this._contact = _contact;
	}


	/**
	 * Return the value associated with the column: Country
	 */
	public java.lang.String getCountry () {
		return _country;
	}

	/**
	 * Set the value related to the column: Country
	 * @param _country the Country value
	 */
	public void setCountry (java.lang.String _country) {
		this._country = _country;
	}


	/**
	 * Return the value associated with the column: Address2
	 */
	public java.lang.String getAddress2 () {
		return _address2;
	}

	/**
	 * Set the value related to the column: Address2
	 * @param _address2 the Address2 value
	 */
	public void setAddress2 (java.lang.String _address2) {
		this._address2 = _address2;
	}


	public String toString () {
		return super.toString();
	}

}